### ISSUE TITLE
[Enhancement][Internals]: Allow Traits to be "Auto-Unlocked"

### ISSUE THREAD

**Issue by Lanse505** [Coders-After-Dark/Reskillable#100]
Add a param or option to have a trait be unlocked by default.

**Comment by pupnewfster** [comment]
This should also potentially allow traits to be auto unlocked when you meet the requirements if the cost of the trait is free.

**Comment by Lanse505** [comment]
sounds good to me

**Comment by pupnewfster** [comment]
One of the ways to do this is to make it so requirements have a partial cache of their state so that it does not have to recheck if the requirement is met for a player each time. For example only have it recalculate a skill level requirement when a player changes level in that skill.
