### ISSUE TITLE
[Enhancement] Stop crafting items that are below player level

### ISSUE THREAD

**Issue by clubpetey** [Coders-After-Dark/Reskillable#108]
I know GameStages/RecipieStages has a feature like this, but the level system of Reskillable is a lot more detailed and I like the UI and trait system.  

The feature could be disabled in the configuration, but when enabled it would not allow a user to craft any item that they do not have all the requirements for.  This could be handled in two ways:

1. Stop the actual crafting, nothing would appear in the output area.
2. Allow the item to craft, but force the player to drop the item as soon as its placed in inventory.  This would be combined with a general rule that a player cannot pickup any item they do not have the requirements for.  If picked up, the player would immediately drop it.  If the item is in a chest, the player cannot remove it from the chest.

I like option 1 a lot better for immersion, but it may be tricky to pull off.

**Comment by Lanse505** [comment]
We are not adding Recipe Gating. 
There is no clean or good way of adding it that doesn't involve a lot of messy code.
It's been discussed and agreed isn't something we are going to be adding.
