### ISSUE TITLE
"none" in config 

### ISSUE THREAD

**Issue by slowiu06** [Coders-After-Dark/Reskillable#114]
Unfortunately, this setting does not work. Everything requires a level 30 farming, when I wanted to exclude these ores from it. I also tried "none" without quotes too...
`        mysticalagriculture=reskillable:farming|30
        mysticalagriculture:inferium_ore:*="none"
        mysticalagriculture:prosperity_ore:*="none"
        mysticalagriculture:nether_inferium_ore:*="none"
        mysticalagriculture:nether_prosperity_ore:*="none"
        mysticalagriculture:end_inferium_ore:*="none"
        mysticalagriculture:end_prosperity_ore:*="none"`

**Comment by pupnewfster** [comment]
Sorry that this does not work. A lot of the config locking stuff broke in the change from Skillable to Reskillable. I thought I had fixed it all but apparently I did not read the line:
```
You can then specify specific items to not be locked,
    # by defining their lock in the normal way. If you want an item to not be locked in this way, use "none" after the =
```

I will work on making sure that this is fixed for the next version. Thank you for the report.
