### ISSUE TITLE
Reskillable needs tweek for gamestage -> OreStages

### ISSUE THREAD

**Issue by royalcw** [Coders-After-Dark/Reskillable#119]
So, I have ores hidden with OreStages.  I use a reskillable custom trait to unlock copper for the player.  OreStages is set to "copper_access" to unhide copper.

What happens:  I get the trait and the gamestage "copper_access" is added to the player.  The ore is still hidden.  If I log out then back in, the ore is unhidden.  

If I manually add "/gamestages add @p copper_access" then the screen flickers/updates and the ores are unhidden.  The screen doesn't flicker/update when GameStageUnlockable is called by compat skills.  I wasn't sure whether to put this here or compat skills.

Desire result:  When the trait below is taken by the player, have the ores made visible through a reload or some update just like gamestages and functions execute when a stage is given to a player.

My trait.  It unlocks the stage correctly but takes a logout/login to actually see the copper ore correctly.
var copper_access = mods.compatskills.GameStageUnlockable.addGameStageUnlockable("copper_access", "copper_access", 2, 0, "reskillable:mining", 1, "stage|stone_age");
copper_access.name = "Copper Explorer";
copper_access.description = "Unlock access to copper resources";

**Comment by Lanse505** [comment]
1) This is a CompatSkills issue not a Reskillable issue.
2) We should be using the appropriate method provided to us by GameStages 2.0 

Gonna get ahold of Darkhax to discuss this.
