### ISSUE TITLE
Crash Upon Left Clicking or Right Clicking on Server

### ISSUE THREAD

**Issue by jjc54** [Coders-After-Dark/Reskillable#125]
Forge: forge-14.23.4.2705
Reskillable: Reskillable-1.12.2-1.7.1
CompatSkills: CompatSkills-1.12.2-1.8.0

Log: https://pastebin.com/gQH1UWpp

**Comment by jjc54** [comment]
My only script for left/right clicking a block:

https://pastebin.com/eDaZcHkc

**Comment by pupnewfster** [comment]
Should be fixed by https://github.com/Coders-After-Dark/Reskillable/commit/bac7df5907cad9f555a352a24f459bb492fad45c
