### ISSUE TITLE
1.7.1 crash when increment skills 

### ISSUE THREAD

**Issue by laneyfamily** [Coders-After-Dark/Reskillable#127]
every time trying to add points to any skill I get a crash using 1.7.1
https://paste.dimdev.org/wimetodipo.mccrash

**Comment by pupnewfster** [comment]
Should be fixed by https://github.com/Coders-After-Dark/Reskillable/commit/bac7df5907cad9f555a352a24f459bb492fad45c I am hoping to release the update tomorrow.

**Comment by laneyfamily** [comment]
Thank you for the update, good to see you were on top of it.  I did not see any open threads so thought I'd post it, should checked the closed ones next time too lol
