### ISSUE TITLE
Advancement Progression Issue

### ISSUE THREAD

**Issue by jjc54** [Coders-After-Dark/Reskillable#128]
Forge: forge-14.23.4.2705
Reskillable: Reskillable-1.12.2-1.8.0
Triumph: Triumph-1.12.2-2.1.1
Sever log: https://www.dropbox.com/s/g352dqvdhbbgqas/latest.log?dl=0

Issue: Using triumph, I set an advancement to unlock upon completion of its parent, which would then unlock a reskillable lock. However, upon completion of the parent advancement nothing happened. I then gave myself the next advancement using commands as a workaround and I had an error. I'm not sure if this is triumph or reskillable as they are both involved in the scripts.

Please let me know if this is a triumph issue.

**Comment by pupnewfster** [comment]
It is a reskillable issue it seems I did not manage to fully fix the CME error though the issue is even replicating what other people have done I tend to be unable to reproduce the issue. So I will look into my implementation tomorrow to see if I make it so it should never produce that error anyways.

**Comment by jjc54** [comment]
Mmk awesome. Let me know if you need anything else, such as my advancement scripts.

**Comment by jjc54** [comment]
Oh also, I just noticed that the advancement properly unlocks upon relogging!

**Comment by pupnewfster** [comment]
Can you please see if https://www.dropbox.com/s/y4ymkvf9wq1iglc/Reskillable-1.12.2-1.8.0.jar?dl=0 fixes it or if it just moves the crash log? I tried to add some checks in to hopefully avoid CMEs but if I have not added enough I want to fix it before releasing a new version on curse.

**Comment by jjc54** [comment]
Sure, I'll try it when I get home tonight. Thanks!

**Comment by jjc54** [comment]
After testing that version on my server, I can confirm that advancements unlock as expected!

**Comment by pupnewfster** [comment]
Ok I will then release a 1.8.1 version on curse tonight or tomorrow.

**Comment by jjc54** [comment]
Awesome, thanks!

**Comment by pupnewfster** [comment]
It is now on curse and has been approved.
