### ISSUE TITLE
Issue adding modded items to Skill Locks

### ISSUE THREAD

**Issue by atxmatt2510** [Coders-After-Dark/Reskillable#129]
Not sure if an issue or I am just doing this incorrectly. I am having difficulty finding documentation on this matter.

Basically I am running a server with various mods that have items I want "skill locked"
I have added lines to the server config as well as trying to do it through the in-game "mod options" menu with no success. Here are a few entries in the config, following the default entries:

```
minecraft:redstone_torch=reskillable:building|5
        minecraft:skull:1=reskillable:building|20,reskillable:attack|20,reskillable:defense|20
		dungeontactics:wooden_shield:*=reskillable:defense|5
		dungeontactics:stone_shield:*=reskillable:defense|6
		dungeontactics:iron_knife:*=reskillable:attack|5,*=reskillable:agility|2
		dungeontactics:iron_cestus:*=reskillable:attack|5,*=reskillable:agility|4
```

This may be a dumb question but I noticed some of the entries have a ":*=" instead of the simple "="
Is there an issue writing my entries with the first method?

I am using "Reskillable-1.12.2-1.8.1"

**Comment by pupnewfster** [comment]
Try using
```
minecraft:redstone_torch=reskillable:building|5
minecraft:skull:1=reskillable:building|20,reskillable:attack|20,reskillable:defense|20
dungeontactics:wooden_shield:*=reskillable:defense|5
dungeontactics:stone_shield:*=reskillable:defense|6
dungeontactics:iron_knife:*=reskillable:attack|5,reskillable:agility|2
dungeontactics:iron_cestus:*=reskillable:attack|5,reskillable:agility|4
```

The `:*` is in general for tools which means it ignores durability. If that still does not work my best guess is that reskillable gets loaded before dungeon tactics in which case I would suggest attempting to use compatskills to add the requirements and see if that works.
The lines you would have to add to a CraftTweaker script for the dungeon tactic items you listed above would be:
```
mods.compatskills.Requirement.addRequirement(<dungeontactics:wooden_shield:*>, "reskillable:defense|5");
mods.compatskills.Requirement.addRequirement(<dungeontactics:stone_shield:*>, "reskillable:defense|6");
mods.compatskills.Requirement.addRequirement(<dungeontactics:iron_knife:*>, "reskillable:attack|5", "reskillable:agility|2");
mods.compatskills.Requirement.addRequirement(<dungeontactics:iron_cestus:*>, "reskillable:attack|5", "reskillable:agility|4");
```

**Comment by Lanse505** [comment]
Has this been fixed so this issue can be closed? @atxmatt2510

**Comment by Lanse505** [comment]
Closing this issue as in-active
