### ISSUE TITLE
[Suggestion] Crafting Need Skill

### ISSUE THREAD

**Issue by GWSheridan** [Coders-After-Dark/Reskillable#13]
Building skill stops crafting of items or add a crafting skill

**Comment by Lanse505** [comment]
After a lot of discussions within the development team.
We've decided that this is not something we think would be feasibly done.
Even @jaredlll08 who has done something similar with RecipeStages agrees it's just a major clusterfuck.

@GWSheridan I'm gonna be closing this issue and marking it as "WontFix".
However with the coming changes to Reskillable, other developers are free to try their hand at implementing it, but it won't be a Reskillable feature.
