### ISSUE TITLE
No Config Descriptions

### ISSUE THREAD

**Issue by Flytre** [Coders-After-Dark/Reskillable#135]
After looking at the config, I have no idea what half the configuration options do. Adding descriptions, or even listing what the options do here would be very welcome!

**Comment by Lanse505** [comment]
I can look into this probably.
Shouldn't be too hard.

However if you have any questions atm throw them in here and I'll try to explain to the best of my ability

**Comment by Flytre** [comment]
Thanks Lanse, I managed to find some change logs that explain the config options!
