### ISSUE TITLE
[Suggestion] Tinkers An Ore Block Hardness 

### ISSUE THREAD

**Issue by GWSheridan** [Coders-After-Dark/Reskillable#14]
Skilled ores an items should not be able to smelt if the skills have not been achieved yet.

Tinkers tools will mine skilled ores as well if you have the skills for another block/ore that has the same hardness allowing you to mine blocks/ores that need skills

**Comment by Lanse505** [comment]
@GWSheridan Okey so:

Smelting Gating: Not possible, needs a player instance we can access which most blocks don't have.

Other Request Written in an archaic language lost to the sands:
Please clarify because I've got nothing but question marks xP

**Comment by darkhax** [comment]
Thanks for the suggestion. With the current smelting system in place it isn't possible to have player based smelting recipes. There are things we could do to get the vanilla furnace working however that solution would not work for modded furnaces or smelting machines. Things like autosmelt would also not work. The smelting system is being overhauled in 1.13 which may make this easier. 

As for the second part, I am not too sure what you mean. Could you try elaborating a bit more? It sounds  possible, but I think I might be misunderstanding you.

**Comment by GWSheridan** [comment]
Ah okay no problem
for the second part
if Ardite from tinkers had 26 skill mining but obsidian had 12. You can place obsidian next to ardite an mine the obsidian with a hammer an it will also mine the ardite as well

**Comment by Lanse505** [comment]
This should be potentially fixed with:
https://github.com/Coders-After-Dark/Reskillable/commit/039b96b4d23b488af3153b216b84cf5b1858bf6c
