### ISSUE TITLE
Crashing shortly after world gen 1.12.2 Forge 2768

### ISSUE THREAD

**Issue by mmmilord** [Coders-After-Dark/Reskillable#141]
Moved the log to Gist: // Lanse
edit: thanks for whoever moved and linked my log first time posting on github lol

mmmilord:
Can't seem to recreate it accurately but all the times it did happen I just walked around the world for a bit in creative with a bow, VanillaFix said that this mod and repose was giving me crashes but after removing repose it still happens. Happens on forge-2796 as well

https://gist.github.com/Lanse505/3d0f78ec30a1c0265dc3dcb153177f0a

**Comment by Lanse505** [comment]
Yea, something is passing a null player to the playertick event, we're looking into it.
No ETA on a fix though unfortunately. 
However, as I said above we are aware of the issue and have a few possible fixes in mind.

I'll update this once we make some progress on this issue in the future.
