### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DevTimur** [Coders-After-Dark/Reskillable#143]
Not sure why, but...
https://pastebin.com/veNU539W

**Comment by Lanse505** [comment]
What dimension where you or the player on your server traveling to?

**Comment by pupnewfster** [comment]
I will look when I get a chance but I think it is due to Galacticraft

Looks like it is a crash due to:
a. An invalid dimension in one of their advancements that we potentially are force checking
b. They have not registered their `moon.moon` dimension by postinit and it is a real dimension name.

**Comment by pupnewfster** [comment]
I was correct that this was due to a conflict with Galacticraft. I have made a chance that stops this crash; however, I still need to do some more testing before pushing it to ensure I did not break anything else.
