### ISSUE TITLE
[Feature Request] If a player cant access to a item it cant be used in craftings

### ISSUE THREAD

**Issue by llchris** [Coders-After-Dark/Reskillable#146]
Hi, I'm asking if this feature may be added. This feature is useful for stage the minecraft gameplay. If a player cant access to an item(not enough skill) it cant be used in craftings.

Thanks - Nov4e

**Comment by Lanse505** [comment]
There is no easy or even clean way to do this due to even how simple inventory or normal crafting works.
I know @pupnewfster has talked about looking into crafting stuff in the past, but in general crafting is something we don't really like to tamper with.

**Comment by pupnewfster** [comment]
When I was messing around with crafting things in the past, it was a pain and Lanse is right that there is no clean way to do it. And that was with seeing if it would be even feasible to have recipe locking in CompatSkills, without also requiring GameStages and RecipeStages and using CompatSkill's GameStage integration. It was not worth the effort for how many other mods handle things differently allowing for bypasses. Not to mention the added calculations for locking components of recipes, given how many recipes there may be.

One thing if ever implemented might more or less work for this would be https://github.com/Coders-After-Dark/CompatSkills/issues/78

However, in 1.13 where recipes will be modifiable with data packs and iirc be sent to the client from the server it may become possible to handle recipes easier.

**Comment by llchris** [comment]
thanks for the help.

**Comment by Lanse505** [comment]
Closing this issue for now, but I've pinned it for future inquiry in 1.13 on-ward.
