### ISSUE TITLE
Autofeeding crashes client/server if Pams harvestcraft food is in inventory

### ISSUE THREAD

**Issue by Surac** [Coders-After-Dark/Reskillable#148]
if the Autofeeding skills tries to consume food from pams Harvestcraft mod it crashes the client/server with a invalid cast exception

**Comment by pupnewfster** [comment]
Two things, one what version are you using, as in 1.12.0 (released yesterday) I fixed a few different crashes with the auto feeding trait, along with some other bugs. And second it would help if you gave us the link to the crash report via pastebin or something if it is still crashing using version 1.12.0

**Comment by Surac** [comment]
Problem solved in version 1.12.0
