### ISSUE TITLE
Reskillable\Nature's Aura Compatibility

### ISSUE THREAD

**Issue by EchoingZen** [Coders-After-Dark/Reskillable#153]
I have been playing the Magiculture 2 modpack (On Twitch Launcher) which contains Reskillable. When attempting to progress in Nature's Aura, it doesn't appear to allow further progress after creating golden leave and gold powder. This SHOULD unlock The Ritual of the Forest entry in the Nature's Aura book, but it does not.

As a test, I moved the following mods and reloaded the world:
* CompatSkills-1.12.2-1.14.1.jar
* extraskills-1.12.2-1.0.2.jar
* Reskillable-1.12.2-1.12.5.jar

After doing this, progression continued as normal. Unfortunately, I don't get an error or crash log so this might be a little tougher to find a solution to.

I have spoken with the Nature's Aura dev and he requested that I post the issue here. Please let me know if there is something else I can do or provide. If needed, I can give you in Twitch Launcher instance folder for Magiculture 2.

**Comment by EchoingZen** [comment]
After yet another restart of the pack trying to figure out what was going on, it suddenly started working. I'm going to close this issue since it's not longer exhibiting the same behavior.

**Comment by aetasoul** [comment]
I have the same issue. I think is not fixed! May I will be lucky as you and it fix just playing with files in the folder

**Comment by facundogomezperez3-wqv** [comment]
DARK

**Comment by facundogomezperez3-wqv** [comment]
# #216
