### ISSUE TITLE
[REQUEST] Add more configurability to Existing Skills

### ISSUE THREAD

**Issue by Cinamonfire** [Coders-After-Dark/Reskillable#161]
Im Kinda Bummed out by this because Im Making my own Reskillable skills using extra skills, attributes, and compatskills but i cant Edit Existing Skill Names or Texture Backgrounds within the Reskillable Config.

And if it were possible to add Block Texture Backgrounds from other mods that would be amazing for extraskills and Reskillable (Because i added Thaumaturgy [Thaumcraft] and Hemomancy [Blood magic] as Custom Skills) so i can relate their block textures to the skill texture background.

These Examples are for a modpack/ modpack server im making so any help is a Blessed deed.

**Comment by pupnewfster** [comment]
In the latest reskillable and compatskills release there is support for changing the backgrounds of existing skills. If you want extraskills to do things you will have to ask them, but personally I would just use CompatSkills as its custom skill creation has a lot more options than extra skills.

In terms of changing existing skill names you should be able to do that just by overriding the lang entries.
