### ISSUE TITLE
Advancement problem with Nature's Aura

### ISSUE THREAD

**Issue by aetasoul** [Coders-After-Dark/Reskillable#162]
I'm having the same issue described here:

https://github.com/Coders-After-Dark/Reskillable/issues/153

Today I have done the same things and the problem solves when I remove this three mods.

If you need more informations I can provide it!
There is no crash or report error. The pack is Magiculture 2. I spoke with the creator of Nature's aura, patchouli and the modpack, nobody know how to solve this.

Thank you in advance.

**Comment by Lupicus** [comment]
I have the same issue with Magiculture 2. It seems to happen with SSP and not SMP.
It is caused by creating new AdvancementManager in ClientProxy.java, which is resetting the advancement list in a client based thread on connect to server and patchouli is checking in the server thread during player login, so the list can be empty sometimes for patchouli.

**Comment by Lupicus** [comment]
I commented out that line and things seem to work for me.

**Comment by MudkipNinja** [comment]
> I commented out that line and things seem to work for me.

I've been having a similar problem with Advent of Ascension! Which line did you comment out?

**Comment by Lupicus** [comment]
In client/base/ClientProxy.java, line 42:
        new AdvancementManager(null);

**Comment by MudkipNinja** [comment]
> In client/base/ClientProxy.java, line 42:
> new AdvancementManager(null);

Thank you for the fast response! I am a little new at this, so could you tell me what you used to edit the class file? Or what you used to decompile/compile it?

**Comment by Lupicus** [comment]
I watched a modding tutorial on setting up a workspace to build this source.
I used JDK 1.8, Eclipse 2019, forge-1.12.2-14.23.5.2815-mdk.zip (which matches Magiculture2 version) and the Reskillable source to build a new jar file.

**Comment by MudkipNinja** [comment]
> I watched a modding tutorial on setting up a workspace to build this source.
> I used JDK 1.8, Eclipse 2019, forge-1.12.2-14.23.5.2815-mdk.zip (which matches Magiculture2 version) and the Reskillable source to build a new jar file.

Thank you for all the replies! I've tried to set this up in eclipse but to no avail. It doesn't recognize the project as an eclipse project with contents. Is there any way you could send me the recoded version if you still have it? If not, thanks for all your help!
