### ISSUE TITLE
[Feature]: Mysql Support

### ISSUE THREAD

**Issue by robertdrakedennis** [Coders-After-Dark/Reskillable#165]
I host a network of severs using this mod. It would be nice to have skill level syncing so that users could make use of it across all of my servers. I'm sure others would like this too.

**Comment by SkySom** [comment]
This is a pretty specific ask, and not something we'd want to support in the main mod. However if someone were to want to build an addon for this specific need, we'd be happy to make sure they have the api and eventing needed to do such a thing.
