### ISSUE TITLE
Levels Resetting

### ISSUE THREAD

**Issue by Powerless001** [Coders-After-Dark/Reskillable#166]
Me and my friend are playing on a lan world. He is hosting. His levels that he puts into things keep resetting back to 1. But my levels stay fine. We have no clue why.

**Comment by pupnewfster** [comment]
Sounds like #164 do you guys have vanillafix?

**Comment by Powerless001** [comment]
yes we do

**Comment by Lanse505** [comment]
Can this be closed @Powerless001 ?

**Comment by Powerless001** [comment]
Yes. Sorry.
