### ISSUE TITLE
My skills are constantly being reset

### ISSUE THREAD

**Issue by bryinabrt** [Coders-After-Dark/Reskillable#168]
For some reason when I upgrade my skills, a few seconds after that they reset back to level 1. I can't figure out as to why is that happening. It didn't happen when I started my world, but later on it started happening. I am using the RLCraft pack if it means anything.

**Comment by pupnewfster** [comment]
Is this the same as #164 ? Was fixed by doing this
`I set the "Optimizations and vanilla bug fixes" to false in Mod Options (for VanillaFix) and havent had skills reset since.`

**Comment by bryinabrt** [comment]
Seems that was the issue, thanks!

**Comment by YoTridex** [comment]
when i download vanilla fix, my game "RLcraft" crashes. there is like a button "Get link" and then it says failed.
