### ISSUE TITLE
Can't figure out custom requirements

### ISSUE THREAD

**Issue by ichimo** [Coders-After-Dark/Reskillable#172]
I looked around a bit and couldn't find anything on how to do the custom requirements for mods.  I know it says and gives examples in the config but thats for the format of specific items and such, but how do I figure out what the mod I'm trying to disable goes by for a name?  I'm trying to put wireless redstone behind a requirement overall but I don't know the format since there wasn't an example for doing the entire mod and I've tried disabling a single item with no luck so far.

**Comment by SkySom** [comment]
I'd take a look at CompatSklls and the crafttweaker integration as it's much better documented. Also the issue tracker is not for questions as those are much better handled by our discord.
