### ISSUE TITLE
Proper Amount of Experience Not Being Used

### ISSUE THREAD

**Issue by Vinegar-Doppio** [Coders-After-Dark/Reskillable#173]
I created an RL craft server a few days ago and have been playing on it a lot. Among the mods I'm using are reskillable and compatskills. Everything was working perfectly with the skills system until yesterday when I noticed the proper amount of xp wasn't being taken from me for my leveling. For example, to increase my attack level I need eight levels worth of experience. If I have eight levels worth and go to increase my attack level, then not all of my eight levels are used, it often only uses four or so. The amount used also seems random, sometimes it will take less than half of the required amount, but never the proper full amount.

**Comment by pupnewfster** [comment]
It takes 8 levels from zero to one, not 8 levels from zero to eight.
