### ISSUE TITLE
one probe or waila compat

### ISSUE THREAD

**Issue by Tyrius1** [Coders-After-Dark/Reskillable#176]
add compat for oneprob or waila to show the requirements.(i just by nature look there) Also might help to overcome the lycanites mobs not showing proper level requirement?

**Comment by pupnewfster** [comment]
Install CompatSkills it has compat for both the one probe, and waila. If it doesn't have support for showing the requirements for entities, you can open an issue on the compatskills issue tracker to add it support for checking an entities requirements.
