### ISSUE TITLE
[Feature request] adding compatibility modded golden tools/weapons/armor with Golden Osmosis skill

### ISSUE THREAD

**Issue by CodeGourami** [Coders-After-Dark/Reskillable#177]
My request is to add modded items to the list of items that get repaired with the Golden Osmosis skill. 
 Items like from bettersurvival, spartan shields and spartan weaponry. They add golden items but they can not be repaired with Golden Osmosis right now. 
Same goes for the golden armor and the golden hoe from vanilla 1.12 minecraft too. They do not get repaired when held (or worn).

Possibly making it so everything with gold or golden in their id is capable of being repaired. 

Thanks a lot for your consideration.

**Comment by pupnewfster** [comment]
This will be included in the next version which I hope to release by the end of the week. I made it so that if a piece of armor or tool is repairable in an anvil using golden ingots then golden osmosis can repair it.
