### ISSUE TITLE
Skill requirements to use Iron and up is 69,420.

### ISSUE THREAD

**Issue by AkilledM** [Coders-After-Dark/Reskillable#184]
I realize the number sounds like a joke, but my friend cant use anything above stone. Minecraft, twitch, modpack reinstalled, all files deleted. Confirmed not server side. Please help, the number seems like it could be the coded max value for attack.
![requirements](https://user-images.githubusercontent.com/58013979/69290247-53c76880-0bcd-11ea-9613-e153a1460065.png)

**Comment by SkySom** [comment]
Whoever configurated the pack probably added that. Not us.
