### ISSUE TITLE
More information?

### ISSUE THREAD

**Issue by TheSexyYeti** [Coders-After-Dark/Reskillable#187]
Where do I go to get more information about completely altering the traits and skills?. I want to do a more D&D style skill tree separated by classes (Warrior, mage, rouge, etc.) and base stats (strength, stamina, Intelligence, etc.). Or should I just go ahead and create a completely new mod Lol.

**Comment by pupnewfster** [comment]
It probably is less work to just create a new mod (especially if you know how to program, and given we aren't really updating this anymore as we are more focused on working on [Epos](https://github.com/The-Acronym-Coders/Epos)). Though if you really want to use Reskillable you can use either the API we provide or attempt to use the CrT integration in CompatSkills that lets you add custom [skills](https://docs.blamejared.com/1.12/en/#Mods/CompatSkills/Supports/Reskillable/CustomSkills/Custom_Skills/) and [traits](https://docs.blamejared.com/1.12/en/#Mods/CompatSkills/Supports/Reskillable/CustomTraits/Custom_Traits/).

Though any further questions are probably more suited for our [discord](https://discord.gg/Q2k3uEe) than for a GitHub issue tracker.
