### ISSUE TITLE
Bug with Biomes O' Plenty's dirt variants

### ISSUE THREAD

**Issue by Phil-M-H** [Coders-After-Dark/Reskillable#188]
BoP adds dirt variants such as sandy dirt.

The green thumb skill causes constant grass tall-grass and flower growth on these dirts.

Also happens with Midnight's 'Midnight Grass'

**Comment by Lanse505** [comment]
not a bug, it's how the trait is implemented.
Currently there is no plan to fix the 1.12 behaviour, it'll most likely be weeded out by the rewrite in 1.15/1.16 that's planned.
