### ISSUE TITLE
[Suggestion] Being Able to Toggle Passive and Active Skills

### ISSUE THREAD

**Issue by smb64** [Coders-After-Dark/Reskillable#189]
I've noticed this talked about a lot on different modpack discords and I'm hoping that is can be added as some passive skills (such as hungry farmer) can become annoying at times.

**Comment by pupnewfster** [comment]
It is unlikely to happen as we have mostly moved development onto Epos and aren't working on 1.12 anymore. I am closing this though as this is a duplicate of #104
