### ISSUE TITLE
Hungry Farmer often feeds items with detrimental effects before those with no effect, or positive effects

### ISSUE THREAD

**Issue by carbohydratesn** [Coders-After-Dark/Reskillable#191]
The Hungry Farmer perk often chooses the worst possible edible items from your inventory.

It's rather frustrating to have an inventory full of bread, then suddenly get hit with hunger, nausea, and wither because the perk decided to have me eat a poisonous raw fish.  Over and over...until I dump all the fish out of my inventory. 

Edible items with negative effects should be chosen last, or should be able to be excluded from auto-feeding.

**Comment by carbohydratesn** [comment]
The best fix may be preferring food based on its position in your inventory.  That would be a very simple way to have the user set their own preferences.  

It currently seems to be alphabetical(?) and that leads to the wrong choice most of the time.

**Comment by pupnewfster** [comment]
This is unlikely to happen as all the developers have moved onto working on 1.15 development of various mods. The way hungry farmer actually works though is it picks the "best" item based on what item gives the most hunger bars/the smallest food needed to fill you back to full. If memory serves there is no way exposed that we can check what potion effects will be applied .

**Comment by carbohydratesn** [comment]
That's a shame.  

If you can't tell what a food will actually do, don't pick randomly for the user; let them choose!  It would be trivial to do it based on inventory position. 

 I'm thankful the license allows for modification and redistribution.

**Comment by carbohydratesn** [comment]
Was this fixed?

**Comment by carbohydratesn** [comment]
@Lanse505 @pupnewfster

**Comment by carbohydratesn** [comment]
Why was this closed if it wasn't fixed?
