### ISSUE TITLE
farmer skill is incompatible with Level Up! Reloaded

### ISSUE THREAD

**Issue by ghost** [Coders-After-Dark/Reskillable#192]
I'm currently playing MC Eternal and used Level Up! Reloaded to level the skill Green Thumb. It gives nearby crops extra growth ticks. After I finished it the growth time of a single crop was near zero. Then I fully skilled Green Thumb from Reskillable and the growth time is now like a little bit faster than without skills. Can I undo the skill from Reskillable or is this a known issue?

**Comment by Renari** [comment]
There's slash commands to reset your skills.
