### ISSUE TITLE
Reskillable conflicts with RFTools' Builder, makes some blocks unmineable

### ISSUE THREAD

**Issue by KirikaAetheria** [Coders-After-Dark/Reskillable#193]
hello, I'm reporting this bug here since it seems to be impossible to fix from RFTools' side

when Reskillable is installed and the RFTools builder is used as a quarry with any of its quarry shape cards, the builder is not able to mine redstone ore, unless that redstone ore is currently glowing/lit. I've only noticed this with redstone, but there could possibly be other blocks where similar conflicts happen. Please refer to this page https://github.com/McJtyMods/RFTools/issues/2038 for examples of what happens, I've taken a few screenshots to document the bug. thank you for your time, and if there's anything I can do on my end, do let me know

**Comment by pupnewfster** [comment]
This is intended, you *can* disable fake players being restricted by requirements in the reskillable config `"Enforce requirements on Fake Players"`

**Comment by KirikaAetheria** [comment]
ah, I see. sorry to bother then, I did not think quarries would count as fake players, because for some reason the buildcraft quarry didn't have any issues. thank you very much for your time
