### ISSUE TITLE
Reskillable breaks Quarries from Buildcraft

### ISSUE THREAD

**Issue by TurboFunder** [Coders-After-Dark/Reskillable#195]
Hello.
    Forge Version: 14.23.5.2847
    BuildCraft Version: 7.99.24.6
    Minecraft version: 1.12.2
    Reskillable version: latest (as of post)

TL:DR - Quarry is a fake player, reskillable requries fake players to meet xp requirement, causes quarry to break.

In the Minecraft mod Buildcraft, their machine called quarry is designed to mine blocks and store them for the player. So the player doesn't have to mine.
The bug is that reskillable causes the quarry top stop as it attempts to mine a locked away block, and requires a player manually mining. 

It is believed that this issue is that the quarry is a fake player, and reskillable requires that even fake players meet the xp levels to interact w/ the block.

Link to the same issue on Buildcraft's github: https://github.com/BuildCraft/BuildCraft/issues/4548
Reskillable compact. mod is also installed and does not fix the issue.

An idea for a fix would be a config setting to disable fake player requirements. 

To Reproduce
    1. Setup a quarry
    2. Make sure Reskillable is installed
    3. Let it run
    4. Will see quarry halt on blocks that are locked away w/ xp. (ex. iron, gold, modded ore as well)

**Comment by pupnewfster** [comment]
This is intended, if you don't want requirements to affect fake players then you should disable the config option `"Enforce Requirements on Fake Players"` in the reskillable config.
