### ISSUE TITLE
Item requirements are not showing on items that i added through config [Reskillable-1.12.2-1.13.0]

### ISSUE THREAD

**Issue by Platchat** [Coders-After-Dark/Reskillable#200]
I have added item requirements to some modded weapons (Spartan Weaponry and a few other) and in game the requirements do not show up and dont even appear active. I am using version 1.12.2-1.13.0.

**Comment by Platchat** [comment]
nevermind i fixed the issue

**Comment by otakup0pe** [comment]
> nevermind i fixed the issue

You should close this issue then 💖

**Comment by hostsys** [comment]
Could you explain how you fixed it please? Am having the exact same issue.

**Comment by madbutcher1212** [comment]
I have the same problem. I've already spent a few days on this. But I don't understand how to make a description.

**Comment by wvltunes** [comment]
I'm having this problem too, could u explain how to fix it pls?
