### ISSUE TITLE
[Question] Is it possible for me to add my own trait?

### ISSUE THREAD

**Issue by ElenaiDev** [Coders-After-Dark/Reskillable#203]
I've been working at this for hours with no success, does anybody know a simple way of doing this or some sourcecode I can look at?

**Comment by pupnewfster** [comment]
Via Reskillable itself no. Via an addon you can, or using CraftTweaker and CompatSkills you are able to create custom traits (https://docs.blamejared.com/1.12/en/Mods/CompatSkills/Supports/Reskillable/CustomTraits/Custom_Traits/)

**Comment by ElenaiDev** [comment]
Thank you for your quick response!

I apologise for not being clear, I'm a mod creator and I'm trying to add a trait to my mod.

Although those are very useful resources.

**Comment by ElenaiDev** [comment]
I figured it out after looking at the original code. I was being stupid,

Thanks for taking the time to reply to my first question, I appreciate it :)
