### ISSUE TITLE
[feature] Prevent players from using pickaxes with certain mining levels until skilled up enough.

### ISSUE THREAD

**Issue by TacocaTYT** [Coders-After-Dark/Reskillable#207]
in order to have compat for silent gear

**Comment by pupnewfster** [comment]
CompatSkills is able to do this

**Comment by TacocaTYT** [comment]
how can it do this? could you enlighten me as i wasn't able to figure it out myself

**Comment by pupnewfster** [comment]
https://github.com/Coders-After-Dark/CompatSkills/blob/master/CHANGELOG.MD#180
