### ISSUE TITLE
Question about Reskillable

### ISSUE THREAD

**Issue by pupnewfster** [Coders-After-Dark/Reskillable#44]
I see that Reskillable is a fork of Skillable, but I was wondering what is different about it as the curseforge page does not say much on the subject. Other than GUI and texture changes are there any differences? Looking at the commits I believe you also are splitting it so it has an API for developers to integrate with it easier (such as your CompatSkills mod).

Is that all the changes so far or are there other mechanic changes implemented / planned.

Note: I do like the idea especially if it makes CompatSkills more possible because having integration with other mods will be useful.

Edit: Also with Reskillable how do you make it so it ignores the NBT of items or will I need to add them through CraftTweaker support added by CompatSkills. The reason I ask is mainly because especially with mods that store energy/fuel using NBT stop being blocked when you fill them up.

**Comment by Lanse505** [comment]
Changelog for Reskillable:
https://gist.github.com/Lanse505/0ae77e6b461ef53c67f365025ae05710

Changelog for CompatSkills:
https://gist.github.com/Lanse505/5c38c7249cc70781215c975b15cb110c

**Comment by Lanse505** [comment]
A lot of the changes atm has been internal, like pretty much a large-scale internal rewrite.

But notable feature changes are:
- Individual Max Level Values per Skill
- Added Support for more advanced staggering costs for Skills
- Added Traits as possible Requirements
- Implemented the ability to Enable/Disable individual Skills
- Fixed a bunch of open issues on Skillable's Issue Tracker
    - Vazkii#23
    - Vazkii#18
    - Vazkii#20 / Vazkii#5
    - #14
    - #11

**Comment by pupnewfster** [comment]
Thank you this is useful information. Regarding my edit, is there a way to make it ignore NBT data, even if it would have to be an option through CompatSkills and CraftTweaker to pass an extra param that specifies NBT data should be ignored?

If not I will try to make do by using CraftTweaker's functions and adding a Reskillable value for each nbt value possible for the item (for example how much power the item has)

**Comment by pupnewfster** [comment]
I also just realized that this is not just an issue with modded items but also causes problems with vanilla ones. Example: Enchant any vanilla tool/armor, the enchantment data is stored using NBT so you can use a diamond sword with attack level 1 just by enchanting it.

**Comment by Lanse505** [comment]
Specific NBT support is included with the CraftTweaker Support Present in CompatSkills.

A Wild-Card value for NBT for the likes of energy costs I do not believe is currently included, hence why I've talked to Jared and Sky about this and it'll be looked into after ModJam is done.

So the enchanted issue shouldn't be too hard to fix by pack authors.
However, we'll look into a wildcard fix.

**Comment by Lanse505** [comment]
Oh wait 🤔 

Just decided to re-read this entire convo and as it stands Reskillable gates the main item, and all other instances of the said item regardless of NBT: 

Example with Tinkers:
https://streamable.com/gvczp

Or at least that's how it should work.

You can also requirement gate **specific** NBT values using the Crafttweaker support in CompatSkills.

So I **think** this issue can be closed now? 
If not I'll reopen it!

**Comment by pupnewfster** [comment]
This is not working as intended as I have all tools for Avaritia having skill requirements, and
https://gyazo.com/e5536e87339a995076be409debe26027
https://gyazo.com/61e8be9e3952a0644e2084dedd607afe
https://gyazo.com/93945e366951c84f1e75b0a543aa3f39

only the ones without NBT data properly have requirements. I think Tinker's Tools may store the data using something other than NBT? Also my example with enchanting vanilla tools breaking it: https://gyazo.com/e23ea8d5897c1a7f0bbdeab96949e3d8

Lookin at the code: https://github.com/Coders-After-Dark/Reskillable/blob/develop/1.12.2/src/main/java/codersafterdark/reskillable/base/LevelLockHandler.java#L80 it appears that it checks to make sure they are both null instead of just if the stored itemstack from the config is null and then ignore the itemstack being checked. (Doing this would cause problems without making it so that there may be a higher required skill for things with specific NBT values.

**Comment by Lanse505** [comment]
I'll dig more into this once Modjam is done.

**Comment by pupnewfster** [comment]
Ok thanks. It also appears that once you use a tool once (so once it is damaged) the skill lockout for the tool goes away. On servers this can let people give diamond picks to someone just starting by just breaking one block with it first. (This is not as big of an issue but still something that probably should be looked into after Modjam.

**Comment by jaredlll08** [comment]
Or you could use the Metadata wildcard.

`<minecraft:diamond_axe:*`

**Comment by pupnewfster** [comment]
Good point I forgot about that for purposes of damage values.

**Comment by pupnewfster** [comment]
I know you guys have some plans to try and fix this (#50 and #51 which are both good ideas for the long term), but as the current attempted fix did not work based on the commit messages, if you want I can try to submit a pull request that fixes the NBT comparison issue (it would behave as you described above, if there is a specific NBT tag that matches a lock it uses that otherwise it uses a base lock if one is specified with no NBT tag). One question though if you want me to create a pull request that fixes the issue; why is the crafttweaker locks and config locks not stored in the same map? (This probably won't make a difference to the algorithm though it would potentially make it slightly cleaner/simpler).

**Comment by Lanse505** [comment]
Feel free to submit a PR with a fix for the issue.

The reason they are on two different lists is something I'm not entirely clear on.
@jaredlll08 is the original author of that part of the code, I'll also talk to him later on about the new suggested changes. 

Once a PR is submitted and things are working we'll look it over and if everything looks good It'll get PR'd.

**Comment by Lanse505** [comment]
@pupnewfster

**Comment by pupnewfster** [comment]
I will start working on one then. In regards to why they are in different maps... it appears that in the last commit (the BROKEN BUILD one) instead of adding them all to locks you attempt to iterate over them. Was there a reason for this or was it just for testing an idea?

**Comment by Lanse505** [comment]
Oh, that was me trying to switch things over to using an Ingredient Stack instead of an ItemStack to support some CrT features.

If you want to redo it in the commit feel free to.
