### ISSUE TITLE
Level 99 Crash

### ISSUE THREAD

**Issue by Mattabase** [Coders-After-Dark/Reskillable#45]
https://goo.gl/p653CE - Crash

https://goo.gl/67EDdf - Config

Here you go Lanse =P

**Comment by Lanse505** [comment]
Invalid, User Error.
Check Discord DMs

**Comment by Mattabase** [comment]
Let it be known, I attempted to do a User Error check with Lanse before sending this here =P

**Comment by Lanse505** [comment]
Let it be known I tried looking at it while running around at work.
