### ISSUE TITLE
No checks for damaged, damageable items

### ISSUE THREAD

**Issue by thebrightspark** [Coders-After-Dark/Reskillable#52]
Hey, I've been just discovered an issue where damaged tools are not affected by skill locks. I am using default configs for the issue described below.

I found that when you get the locks for an item, you always compare metadata to see if it has the wildcard value or if the metadata exactly match. This means that for example someone with the skill requirements for a Diamond Pickaxe could give someone who doesn't a damaged one, and they'll be able to use it fine.

Here's screenshots of an undamaged and damaged Diamond Pickaxe to show the tooltips:
![Undamaged](https://user-images.githubusercontent.com/11932411/38383503-97efc6bc-3904-11e8-8884-8911307f3f05.png)
![Damaged](https://user-images.githubusercontent.com/11932411/38383510-9bc6dd70-3904-11e8-8526-486bbd764051.png)

I believe it would make sense if you checked if the item is damageable first somewhere. Perhaps when you read the lock configs to set any damageable items without defined metadata to the wildcard metadata?

**Comment by Lanse505** [comment]
Known issue, this will be adressed along side the NBT issues, be aware this is limited to Config entries as far as I know.

If you reproduce the lock using the CrT support provided by CompatSkills and do something like:
<minecraft:diamond_pickaxe:*> it'll wildcard the metadata should work.

**Comment by Lanse505** [comment]
See #44  for the NBT discussion and #50 for what we "might" be doing to fix it.

**Comment by thebrightspark** [comment]
Ah good to know you're already aware and on it :)

Will give that a go, thanks.

**Comment by thebrightspark** [comment]
Oh just a thought, if I set the metadata in the config to 32767 that should work right?
Just thinking that from looking at your comparison method you use here:
https://github.com/Coders-After-Dark/Reskillable/blob/release/1.12.2/src/main/java/codersafterdark/reskillable/base/LevelLockHandler.java#L100

**Comment by thebrightspark** [comment]
Tested what I was trying to explain above and doesn't work unfortunately. I'll use the CrT support as you mentioned.
