### ISSUE TITLE
Mod Support (Friendly Suggestion)

### ISSUE THREAD

**Issue by ghost** [Coders-After-Dark/Reskillable#58]
As i remember there wasn't modded weapons support in this mod. Can you add it? Algorith would be simple. For example, for swords/knives; multiply the attack speed and damage then specify the required level/exp for it... I mean catch the A.D. and A. speed of the weapon if possible. It was just an example. You can decide how it will work. It would be very fun. Thanks.

**Comment by Lanse505** [comment]
Reskillable does not alter tools or weapons attributes (mining level, attack speed, attack damage, etc).

It's also out-of-scope of the mod.
However if someone would like to make an addon to support that, they can feel free to.
However, it, unfortunately, won't be a feature in Reskillable.
