### ISSUE TITLE
Locking whole mods; Confused

### ISSUE THREAD

**Issue by 8BrickDMG** [Coders-After-Dark/Reskillable#59]
Hello,

I read this in the config and am a bit confused about it:

``You can lock entire mods by just using their name as the left argument. You can then specify specific items to not be locked, by defining their lock in the normal way. If you want an item to not be locked in this way, use "none" after the =``

Does this mean I should be able to do the following?:

``twilightforest=adv|minecraft:end/kill_dragon``

**Comment by Lanse505** [comment]
That should be the case, however be aware that we have done a lot of internal rewrites especially to the lovk system, so it might not work.

If it doesnt shoot a message in here and Ill look into getting it fixed.

**Comment by 8BrickDMG** [comment]
That’s cool. In which case it doesn’t work in the latest build.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Lanse505** [comment]
1) will look into
2) why did you append you message with a shady link to getting outlook for ios....

**Comment by 8BrickDMG** [comment]
Thanks! Apologies for the link, I sent it directly from my outlook account and the default signature was still on.

________________________________
