### ISSUE TITLE
Locking entire mod does not work

### ISSUE THREAD

**Issue by PssbleTrngle** [Coders-After-Dark/Reskillable#65]
The configuration file states that, in order to lock an entire mod, one should just use the modid as the left-side argument, but the following line does not work:
`botania=reskillable:magic|5`

Did I misunderstand something?

**Comment by Lanse505** [comment]
@pupnewfster

**Comment by Lanse505** [comment]
What Reskillable Version are you using?

**Comment by PssbleTrngle** [comment]
1.12.2-1.1.0, just released there is an update.
I will try it with the new version and let you know if it worked

**Comment by Lanse505** [comment]
Yea the mod locking got re-added in the 1.2.0 build of Reskillable.
1.1.0 does not support mod locking.

Closing this issue since it's a outdated version.

**Comment by Lanse505** [comment]
P.s: We did some testing with 1.2.0 once you opened this issue and it works.

**Comment by PssbleTrngle** [comment]
Thank you very much
