### ISSUE TITLE
HorseArmor and Saddle when putting on horse ignores skill requirements

### ISSUE THREAD

**Issue by ilvrak** [Coders-After-Dark/Reskillable#70]
make it like putting armor on player

**Comment by Lanse505** [comment]
We've discussed this in the past and there is no good way of implementing this.
If an addon mod can figure out how to do it, that'd be fine.

However, from our internal discussions, we've agreed that this isn't something we'd be doing in Reskillable.

**Comment by ilvrak** [comment]
I thought it was easier than actually, and its just a bug
thanks for the explanation!
