### ISSUE TITLE
skill icon changes not proportional to skillcap

### ISSUE THREAD

**Issue by ilvrak** [Coders-After-Dark/Reskillable#71]
skill icon changes every 4 points, but it has only 4 stages, ang skillcap - 32
after 12 - it stops, but skills continue to increase to 32

**Comment by Lanse505** [comment]
That's because we've only got 4 icons and 8 ranks.
Unfortunately, we don't have a dedicated Texture Artists attached to the project so until we find one willing to help provide a texture overhaul/extension, we're kind of stuck on this one.

**Comment by ilvrak** [comment]
i mean - need to only stretch change of the icon proportional to levelcap. if levelcap - 32 - icon must change every 8 skills. not 4
like in original Skillable
