### ISSUE TITLE
How current stagger system works?

### ISSUE THREAD

**Issue by ilvrak** [Coders-After-Dark/Reskillable#76]
I don't understand how stagger system works now.
I want 1-4 skill cost 1
5-8 skill cost 2
etc

in original skillable it was - cost increase every X levels
now it is possible to do?

**Comment by Lanse505** [comment]
Explaination:
https://i.imgur.com/qITwtYD.png

Don't think it's possible to do what you want to do currently.
Unless negative stagger cost values are possible which I'm 98% sure it doesnt.
@SkySom could correct me though.

**Comment by srwaggon** [comment]
For posterity:

![qITwtYD](https://user-images.githubusercontent.com/1132359/150610303-b41d5afe-72e2-4514-9b55-d5ec179a4293.png)
