### ISSUE TITLE
[Enhancement]: JEI tooltip compatibility/performance improvement

### ISSUE THREAD

**Issue by pupnewfster** [Coders-After-Dark/Reskillable#77]
While working on some changes for my next pull request I noticed that JEI runs the onTooltip event for all items. (I believe that this is how they allow searching item tooltips.)

For performance reasons I recommend we do one of the following.
- change our onTooltip listener to only start once JEI has finished indexing the tooltips of all items
- change it so that until JEI has finished indexing the tooltips we default to displaying the extended information in onTooltip.

The reasoning for this is because at the moment there is not much point in scanning all items for locks (even though this is more as an edge case problem of if there are an extremely large number of locks set) as JEI only caches the "Hold SHIFT for requirements" part of our tooltip.

The first solution I gave above has the benefits of not having to calculate the locks of all items, while the second one has the benefits of allowing someone to search for "magic" and see all items that are locked behind a magic level.

**Comment by pupnewfster** [comment]
If I understand correctly from an error log someone had in discord, it seems JEI calls onToolTip with a null player. So potentially for retrieving the tooltip we should make it so that if PlayerData is null then it treats requirements as not obtained.

**Comment by mezz** [comment]
JEI runs the tooltip scan on `FMLLoadCompleteEvent`. This is the last loading stage on the loading screen.

If you only want to affect tooltips in-game, you could add your tooltip hook on `FMLNetworkEvent.ClientConnectedToServerEvent` and remove it on `FMLNetworkEvent.ClientDisconnectionFromServerEvent`
