### ISSUE TITLE
Trait Request

### ISSUE THREAD

**Issue by royalcw** [Coders-After-Dark/Reskillable#88]
Would love to see a step assist (not jump assist) trait under the agility skill.  Cyclic mod has an apple that you eat that gives step up and he states that his code is free to use for anyone for anything.  Code and authorization to use for the step assist is @ https://github.com/PrinceOfAmber/Cyclic/blob/master/src/main/java/com/lothrazar/cyclicmagic/item/food/ItemAppleStep.java

**Comment by Lanse505** [comment]
Implemented and Done, will be in 1.4.0
