### ISSUE TITLE
[Config]Option to disable using exp to level skills

### ISSUE THREAD

**Issue by thephoenixlodge** [Coders-After-Dark/Reskillable#93]
As I discussed with Lanse last night, I'd like to be able to disable the ability to level up skills with exp in the gui. While this may not make a lot of sense at first glance, the fact that there are the commands for levelling skills means I should be able to use the likes of advancements, dummy items (added with ContentTweaker) or perhaps scoreboard achieves to provide the levelling functionality, potentially in ways that are more relevant to the use of the skill.

**Comment by pupnewfster** [comment]
I know you can lock skills using CompatSkills, also for making a skill cost 0 xp you can set the "base level cost" to 0 and "level staggering" to `0|0`

**Comment by Lanse505** [comment]
That's not what Phoenix means, he/she is looking for an config option to disable the level-up button so people can't level-up a skill using Experience.

I've got a semi-functional implementation under the 1.5.0 branch I've created.
https://github.com/Coders-After-Dark/Reskillable/commit/00d4a28de95890af404675d64bff7268bc3de0d4
